version: "3"

services:

  # Interface to se logs from the other docker
  dozzle:  
      image: amir20/dozzle:v3.10.1
      network_mode: host
      restart: always

      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

      environment:
        DOZZLE_ADDR: "0.0.0.0:9000"
        DOZZLE_USERNAME: ""
        DOZZLE_PASSWORD: ""
  
  # mongodb
  mongo:
    image: "mongo:4.0.24-xenial"
    container_name: mongo

    volumes:
      - ./data/mongo:/data/db
    
    ports:
      - "27017:27017"

    env_file:
      - .env

    environment: 
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    
    command:
      mongod

  # mongodb web interface
  mongo_express:
    image: mongo-express
    restart: always

    ports:
      - "8081:8081"

    depends_on:
      - "mongo"
    links:
      - mongo    

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: ""
      ME_CONFIG_BASICAUTH_PASSWORD: ""
  
  backend:
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

    volumes:
      - .:/backend

    command: "gunicorn --log-level INFO -b 0.0.0.0:8000 -w 1 -k uvicorn.workers.UvicornWorker backend.main:app --access-logfile '-'"

    depends_on:
      - mongo
    links:
      - mongo 